# Generated by Django 4.1.7 on 2023-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(default='', max_length=140)),
                ('ubicacion', models.CharField(max_length=100)),
                ('cuerpo', models.TextField(default='')),
                ('autor', models.CharField(default='', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
