# Generated by Django 4.1.7 on 2023-04-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='articulos'),
        ),
    ]
